name: splatposeplus
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit-dev
  - plyfile
  - python=3.11
  - pip
  - tqdm
  - glm
  - pytorch
  - torchaudio
  - torchvision
  - matplotlib
  - Pillow
  - scipy
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - opencv-python
    - easydict
    - einops
    - kornia
    - yacs
    - scikit_learn
    - pycolmap
